### ISSUE TITLE
Hiding console logs in production

### ISSUE THREAD

**Issue by acagastya** [mhoran/weechatRN#34]
Hi, I was trying weechatRN today on expo, and I noticed multiple times the data was logged in the console -- I believe for debugging purpose.

Could you please add a way it is not logged in production (for example, when doing `expo publish`)?

**Comment by mhoran** [comment]
Not sure how to do this off hand but I'll look into it! I honestly don't even know where the logs go in the production build but it would be good to shut off the logging there regardless (or at least make it configurable).

**Comment by acagastya** [comment]
One way of doing it could be setting up `NODE_ENV=DEVELOPMENT` in `.env` file and doing `process.env.NODE_ENV == "DEVELOPMENT" && console.log('debug info.')`.

Or, `console.debug = (...arguments) => process.env.NODE_ENV == "DEVELOPMENT" && console.log(...arguments)`

Probably not the best way to do it, but this could be used.

**Comment by mhoran** [comment]
I have confirmed that production builds do not log. If you run expo locally with `--no-dev`, there are no logs written to the console. Perhaps this was changed in a recent release of Expo.
