### ISSUE TITLE
Tweaking the styles of messages

### ISSUE THREAD

**Issue by acagastya** [mhoran/weechatRN#35]
Hi, I have been using weechatRN via expo since yesterday and the best part of it is: it is simple, is not bloated, and it works perfectly.

However, there are a few things I think there are a few things that could be improved:
1. The font size.  Current font-size seems to be too tiny.  Font sizes are subjective -- what is normal for one could be huge for others -- would you please consider increasing the font size, or giving an option to set custon font size?
2. Sender's name.  Currently, the font size of the sender's name is smaller than the message, making it harder to distinguish who sent the message.  Could you please make the nick of the sender bigger than the font size of the messages?
+ Additionally, could you add provisions like in the first photo, so the first letter of the nick is displayed in a circle -- this could help in many small channels, or those were only a handful are actually active, to easily distinguish.
![IMAGE 2020-11-09 21:39:13](https://user-images.githubusercontent.com/5466083/98565773-03608380-22d4-11eb-8922-88d629b0b43f.jpg)
3. Could you make the batches jons, parts and quits collapsed by default, and have a different background colour?
+ There are a lot of joins and quits in a channel.  Them taking too much space with same background colour makes it harder to read the message, and important messages are lost sometimes.
+ Instead of displaying one in the red by default, display the one in green.  And when one taps on it, display the red, and one taps again, toggle it again.
```diff
-- --> foo joined the channel
-- <-- bar quit
-- <-- baz parted
-- --> bar joined the channel
-- <-- bar quit
++ --> 2 joined, 3 left
```
4. Make the channel list and PM alphabetically sorted -- that way it will be easier to navigate.

**Comment by mhoran** [comment]
I can definitely do something about 1 and 2.

For 3, I would recommend using weechat's smart filter. See https://weechat.org/files/doc/devel/weechat_faq.en.html#filter_irc_join_part_quit (the first example). That will only show join/part/quit messages from people who are actively contributing to the conversation. This makes things work across relay clients (weechat-android and weechatRN) as well as the weechat client itself.

**Comment by acagastya** [comment]
All right, thanks!

**Comment by acagastya** [comment]
![9736A6CA-2936-41D2-A9A3-0D5053915636](https://user-images.githubusercontent.com/5466083/98581932-3d3b8500-22e8-11eb-977b-bbbeb371bb0f.png)
![EAE38BA8-4315-46B4-AE4F-2A747A115723](https://user-images.githubusercontent.com/5466083/98581938-40367580-22e8-11eb-93a3-f29df86601d4.png)

I implemented sorting channels by name and changed the font size, as well as family.  What do you think, @mhoran?

**Comment by mhoran** [comment]
re: sorting, weechatRN currently sorts according to weechat buffer order. So if you don't have weechat buffers sorted alphabetically, then they won't be sorted that way in the client. I think this makes the most sense and it's the way we do it in weechat-android too. There exist multiple weechat plugins to sort the buffers alphabetically and then that would be reflected in weechatRN. See https://weechat.org/scripts/source/autosort.py.html/ for example. I'm hesitant to change this behavior in weechatRN.

I'd like to make the font size configurable as I agree that it's quite subjective. We've done this in weechat-android as well. It's a bit difficult to introduce new preferences at the moment but I'll take a look and see what I can do.

**Comment by acagastya** [comment]
I meant to ask, how does the layout look now?  Not the font-size, but the spacing of elements to distinguish.

**Comment by acagastya** [comment]
@mhoran a couple of more suggestions.

1. Change the colour of the "#" symbol if there are new messages.  Better if it can tell the difference between messages in channel vs PM.  Even better if it shows the count.
2. Change the background of channels which are inactive.  (Those channels which the user has parted.)

Could you please implement these?  I would see if I can figure out a way.

**Comment by mhoran** [comment]
> I meant to ask, how does the layout look now? Not the font-size, but the spacing of elements to distinguish.

I think the spacing looks good! I really like the proposal in your first post -- just have to find the time to make that happen!

> Change the colour of the "#" symbol if there are new messages. Better if it can tell the difference between messages in channel vs PM. Even better if it shows the count.

Yes! I thought I already had an issue for that but I guess not.

> Change the background of channels which are inactive. (Those channels which the user has parted.)

This is a bit of weird weechat UX thing. But basically, you want to use `/close` instead of just `/part`. That'll make the buffer close as well as part.

**Comment by acagastya** [comment]
Re the background colour for inactive channels, there are some channels which the user wants to join on a later point in time, and there are channels they don't want in buffer.  For those where the user `/part`s, it would be nice to have a different colour.

Additionally, for parted channels, if there was a banner at the bottom of the screen which said "rejoin", that would be nice.

But again, this is a minimalist app, as of now.  And my feature suggestions/request might add unnecessary complications.

If my suggestion/requests go against your idea behind the app, please feel free to point out!

**Comment by acagastya** [comment]
By the way, I think the colour of "#" changes when there are messages.

**Comment by mhoran** [comment]
> Re the background colour for inactive channels, there are some channels which the user wants to join on a later point in time, and there are channels they don't want in buffer. For those where the user /parts, it would be nice to have a different colour.

> Additionally, for parted channels, if there was a banner at the bottom of the screen which said "rejoin", that would be nice.

I looked into this a bit today and there's no good way to figure this out with maintaining extra state in weechatRN. weechat itself doesn't really treat "inactive" buffers any differently; when you `/part`, there's no specific state or relay message so far as I can see to indicate this.

Right now we mirror the behavior of weechat-android (it just shows the channel as is) so I think I'll leave this as is for now. But if the behavior changes itself in weechat at some point then I'll reconsider. FWIW, weechat itself doesn't disable the input box in any way; if you send text to a parted channel you get "No such nick/channel".

**Comment by mhoran** [comment]
I have brought the style of messages in line with WeeChat, so the prefix (nick) is displayed to the left of the message. This should resolve issues in distinguishing who sent a given message.

I've also bumped up the default font size.

The other items (hiding join/part and sorting the buffer list) are best handled in WeeChat itself, as discussed.

Thanks for proposing these improvements!
