### ISSUE TITLE
Github Actions error

### ISSUE THREAD

**Issue by Forum-G** [mhoran/weechatRN#38]
Hi, I am trying to test similar workflow like you but I keep on getting this error  - Logging in...
14
✔ Logged in, verify your Apple account to continue
15
[18:25:13] Two-factor Authentication (6 digit code) is enabled for ***. Learn more: https://support.apple.com/en-us/HT204915
16
✖ Logging in...
17
[18:25:13]
18
[18:25:13] Authentication with Apple Developer Portal failed!
19
[18:25:13] Input is required, but Expo CLI is in non-interactive mode.
20
Required input:
21
> How do you want to validate your account?
22
[18:25:13] Error: Input is required, but Expo CLI is in non-interactive mode.
23
Required input:
24
> How do you want to validate your account?
25
    at prompt (/Users/runner/hostedtoolcache/expo-cli/4.9.0/x64/node_modules/@expo/apple-utils/build/index.js:1:949954)
26
    at Object.toggleConfirmAsync (/Users/runner/hostedtoolcache/expo-cli/4.9.0/x64/node_modules/@expo/apple-utils/build/index.js:1:950717)

Because 2fa is enabled , workflow fails as the 6 digit code pops up but there is no way to bypass it, how have you done it ?

**Comment by mhoran** [comment]
Hey @ForumG-SC. You'll need to set the `FASTLANE_SESSION` environment variable, the contents of which can be generated via the `fastlane spaceauth` command on another machine. The session token is good for 30 days, at which point you'll have to generate it again.

**Comment by Forum-G** [comment]
I already did that still it fails because of 2fa authentication!

**Comment by Forum-G** [comment]
> Hey @ForumG-SC. You'll need to set the `FASTLANE_SESSION` environment variable, the contents of which can be generated via the `fastlane spaceauth` command on another machine. The session token is good for 30 days, at which point you'll have to generate it again.

Hi , I did create fastlane session variable in the secret and gave the value , I ran this command fastlane spaceauth -u YOUR_APP_STORE_EMAIL, it generated the session and I added that as value in the secret! Yet it throws the same error that I have mentioned in this issue.

**Comment by mhoran** [comment]
Hmm. I'm not sure what could be going wrong. You can see my steps here: https://github.com/mhoran/weechatRN/blob/master/.github/workflows/publish.yml#L27-L32. I have both a `FASTLANE_SESSION` and a `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`. I believe both are needed; the app specific password for the upload process but the session for other steps. You can see the flow for the upload here: https://github.com/mhoran/weechatRN/runs/3104686050?check_suite_focus=true#step:9:1.

You might also want to make sure you copied the `FASTLANE_SESSION` exactly. It's kinda wonky, a very long string embedded in quotes with \n characters. If anything gets messed up then it will become corrupt and not work.

**Comment by Forum-G** [comment]
> Hmm. I'm not sure what could be going wrong. You can see my steps here: https://github.com/mhoran/weechatRN/blob/master/.github/workflows/publish.yml#L27-L32. I have both a `FASTLANE_SESSION` and a `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`. I believe both are needed; the app specific password for the upload process but the session for other steps. You can see the flow for the upload here: https://github.com/mhoran/weechatRN/runs/3104686050?check_suite_focus=true#step:9:1.
> 
> You might also want to make sure you copied the `FASTLANE_SESSION` exactly. It's kinda wonky, a very long string embedded in quotes with \n characters. If anything gets messed up then it will become corrupt and not work.

Yes I have both the secrets added. I was wondering is there a way to use app store connect api key instead of session.. not sure why this is not working

**Comment by Forum-G** [comment]
> > Hmm. I'm not sure what could be going wrong. You can see my steps here: https://github.com/mhoran/weechatRN/blob/master/.github/workflows/publish.yml#L27-L32. I have both a `FASTLANE_SESSION` and a `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`. I believe both are needed; the app specific password for the upload process but the session for other steps. You can see the flow for the upload here: https://github.com/mhoran/weechatRN/runs/3104686050?check_suite_focus=true#step:9:1.
> > You might also want to make sure you copied the `FASTLANE_SESSION` exactly. It's kinda wonky, a very long string embedded in quotes with \n characters. If anything gets messed up then it will become corrupt and not work.
> 
> Yes I have both the secrets added!!

![image](https://user-images.githubusercontent.com/84411852/127723507-7ea67615-182e-4c94-a405-9003aeb10a7b.png)

everytime I run the actions, on my mobile phone 6 digits code appear, idk how to bypass 2fa  than here it fails

**Comment by Forum-G** [comment]
@mhoran Hi, I was reading ur .gitignore file and realized that your repo does have fastlane folder with some configuration details , i guess to make ci cd work not only i need yml file but also some fastlane stuff in my repo, can you share the steps to set that up??

**Comment by mhoran** [comment]
I checked but there's nothing in a `fastlane` directory locally. The `.gitignore` was auto-generated by Expo when the project was initialized.

Looking at your logs, they're a bit different than mine. Have you ever run a Expo build locally? I have done that previously, and I wonder if that's the difference. My provisioning profile is already set up, so the Expo iOS build doesn't need my Apple creds. If you look at my build logs, you'll see the following:

```
[14:09:17] Accessing credentials for *** in project WeechatRN
[14:09:18] Unable to validate distribution certificate due to insufficient Apple Credentials
[14:09:18] Unable to validate Push Keys due to insufficient Apple Credentials
- Performing best effort validation of Provisioning Profile...
```

However, your build fails at this point due to 2fa.

**Comment by Forum-G** [comment]
> I checked but there's nothing in a `fastlane` directory locally. The `.gitignore` was auto-generated by Expo when the project was initialized.
> 
> 
> 
> Looking at your logs, they're a bit different than mine. Have you ever run a Expo build locally? I have done that previously, and I wonder if that's the difference. My provisioning profile is already set up, so the Expo iOS build doesn't need my Apple creds. If you look at my build logs, you'll see the following:
> 
> 
> 
> ```
> 
> [14:09:17] Accessing credentials for *** in project WeechatRN
> 
> [14:09:18] Unable to validate distribution certificate due to insufficient Apple Credentials
> 
> [14:09:18] Unable to validate Push Keys due to insufficient Apple Credentials
> 
> - Performing best effort validation of Provisioning Profile...
> 
> ```
> 
> 
> 
> However, your build fails at this point due to 2fa.

No, I haven't done expo build locally. So , do you mean that I need to first manually do expo build from cli and than try github actions ? Also, no need to setup fastlane from cli ?? All I did was i generated session from cli in vs code and pasted in secret in github and added other secret credentials like expo , apple , etc and used the script in yml file to run but it always fails because 6 digit code generates on my phone the fastlane is doing nothing here so I was wondering if u did any pre steps that i need to follow ? 

I just added provisioning profile to my developer's account , do I need to match anything in app.json file with that profile?

**Comment by Forum-G** [comment]
> I checked but there's nothing in a `fastlane` directory locally. The `.gitignore` was auto-generated by Expo when the project was initialized.
> 
> Looking at your logs, they're a bit different than mine. Have you ever run a Expo build locally? I have done that previously, and I wonder if that's the difference. My provisioning profile is already set up, so the Expo iOS build doesn't need my Apple creds. If you look at my build logs, you'll see the following:
> 
> ```
> [14:09:17] Accessing credentials for *** in project WeechatRN
> [14:09:18] Unable to validate distribution certificate due to insufficient Apple Credentials
> [14:09:18] Unable to validate Push Keys due to insufficient Apple Credentials
> - Performing best effort validation of Provisioning Profile...
> ```
> 
> However, your build fails at this point due to 2fa.

<img width="1423" alt="Screen Shot 2021-08-03 at 2 44 39 AM" src="https://user-images.githubusercontent.com/84411852/127970134-4f3b5914-3301-4413-9377-1804716609a6.png">

After setting up the provisioning profile , I ran my GitHub action again and got this error, while the script was running 6 digit code pop-up on my laptop screen and 2fa failed

**Comment by mhoran** [comment]
When you set up the provisioning profile did you set it up so that Expo manages it? I have that set up entirely so Expo manages the profile (I believe that's one of the options). It still looks like you're getting into a different flow here for some reason.

Did the `expo build:ios` locally succeed?

**Comment by Forum-G** [comment]
> When you set up the provisioning profile did you set it up so that Expo manages it? I have that set up entirely so Expo manages the profile (I believe that's one of the options). It still looks like you're getting into a different flow here for some reason.
> 
> Did the `expo build:ios` locally succeed?

I dont think so as i already have 2 push keys and it is not generating new one or using the existing and it says provisioning profile missing, i see bundle identifier,team id and team name. 
![image](https://user-images.githubusercontent.com/84411852/128031051-40588f1f-e3f5-44e0-8e5d-ffbcd1439e31.png)

**Comment by Forum-G** [comment]
I have revoke old key and now expo build succeed locally

**Comment by mhoran** [comment]
Excellent. I think it should work on CI now.

**Comment by Forum-G** [comment]
> Excellent. I think it should work on CI now.

I hope so , I am testing right now , so basically Fastlane sessions makes the 2fa skip or bypass right? Because I see 6 digit code on my screen , when you run your workflow do you also get 6 digit code ?

**Comment by mhoran** [comment]
I do not get any push notification when I run in CI. However, the 
`FASTLANE_SESSION` only works with the fastlane CLI, not the Expo CLI.  
Your build is failing with the Expo CLI (not even getting to the 
fastlane CLI.

**Comment by Forum-G** [comment]
> I do not get any push notification when I run in CI. However, the `FASTLANE_SESSION` only works with the fastlane CLI, not the Expo CLI. Your build is failing with the Expo CLI (not even getting to the fastlane CLI.

your workflow name is publish to TestFlight so after successfully running the script, in expo.io dashboard the iOS build gets ready there but from there does it automatically gets sent to TestFlight ??

**Comment by mhoran** [comment]
The Expo CLI used to (maybe still does) have a `upload:ios` command, but 
it never worked very well. I switched to using `fastlane pilot upload` 
directly, which requires that I pull down the `.ipa` built by `expo 
build:ios` with curl.

https://github.com/mhoran/weechatRN/blob/master/.github/workflows/publish.yml#L27-L32

See 
https://github.com/mhoran/weechatRN/commit/02e047a30bae848cffc2c8e0c46a5f9294e3ccbc#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7 
for the change.

**Comment by Forum-G** [comment]
> The Expo CLI used to (maybe still does) have a `upload:ios` command, but it never worked very well. I switched to using `fastlane pilot upload` directly, which requires that I pull down the `.ipa` built by `expo build:ios` with curl. https://github.com/mhoran/weechatRN/blob/master/.github/workflows/publish.yml#L27-L32 See [02e047a#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7](https://github.com/mhoran/weechatRN/commit/02e047a30bae848cffc2c8e0c46a5f9294e3ccbc#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7) for the change.

Very helpful thanks, I am testing my workflow and its in progress (running from 24 mins) but the good part is by building expo locally once removed the old error . Hopefully it gets built successfully and gets published to TestFlight.

**Comment by Forum-G** [comment]
2fa :( error
![image](https://user-images.githubusercontent.com/84411852/128048685-476582e3-4aba-4bc6-b247-1a300536cf38.png)

[16:01:58]: 
[16:01:58]: $ [sudo] gem cleanup
[16:01:58]: 
[16:01:58]: to uninstall outdated gems and make fastlane launch faster
[16:01:58]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[16:01:58]: To get started with a Gemfile, run
[16:01:58]: 
[16:01:58]: $ bundle init
[16:01:58]: $ echo 'gem "fastlane"' >> Gemfile
[16:01:58]: $ bundle install
[16:01:58]: 
[16:01:58]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[16:01:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:02:00]: Sending anonymous analytics information
[16:02:00]: Learn more at https://docs.fastlane.tools/#metrics
[16:02:00]: No personal or sensitive data is sent.
[16:02:00]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[16:02:00]: Login to App Store Connect (***)
Session loaded from environment variable is not valid. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account '***'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship_2fa_sms_default_phone_number)

Please enter the 6 digit code:
Requesting session...

Looking for related GitHub issues on fastlane/fastlane...

➡️  `download_dsyms` fails to use session from spaceauth
    https://github.com/fastlane/fastlane/issues/18763 [closed] 2 💬
    3 weeks ago

➡️  match permission denied
    https://github.com/fastlane/fastlane/issues/17810 [closed] 11 💬

    26 Apr 2021

[!] The request could not be completed because:
	Unauthorized Access
➡️  Exception type: Spaceship::UnauthorizedAccessError
    https://github.com/fastlane/fastlane/issues/16510 [closed] 35 💬
    17 Sep 2020

and 21 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Error: Process completed with exit code 1.

**Comment by mhoran** [comment]
It looks like you got past the Expo build though, that's good. So now it's just a `fastlane` issue. I imagine the `FASTLANE_SESSION` environment variable might be incorrect, or perhaps the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`. You must also pass `FASTLANE_USER` and `FASTLANE_PASSWORD`. I think you're very close now though, it should just be some tweaking of those environment variables. You shouldn't see anything about 2fa in the output if it's working.

**Comment by Forum-G** [comment]
Pilot failed:
8s
1
Run fastlane pilot upload
10
[16:01:58]: Seems like launching fastlane takes a while - please run
11
[16:01:58]: 
12
[16:01:58]: $ [sudo] gem cleanup
13
[16:01:58]: 
14
[16:01:58]: to uninstall outdated gems and make fastlane launch faster
15
[16:01:58]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
16
[16:01:58]: To get started with a Gemfile, run
17
[16:01:58]: 
18
[16:01:58]: $ bundle init
19
[16:01:58]: $ echo 'gem "fastlane"' >> Gemfile
20
[16:01:58]: $ bundle install
21
[16:01:58]: 
22
[16:01:58]: After creating the Gemfile and Gemfile.lock, commit those files into version control
23
[16:01:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
24
[16:02:00]: Sending anonymous analytics information
25
[16:02:00]: Learn more at https://docs.fastlane.tools/#metrics
26
[16:02:00]: No personal or sensitive data is sent.
27
[16:02:00]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
28
[16:02:00]: Login to App Store Connect (***)
29
Session loaded from environment variable is not valid. Continuing with normal login.
30
Two-factor Authentication (6 digits code) is enabled for account '***'
31
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915
32

33
If you're running this in a non-interactive session (e.g. server or CI)
34
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
35

36
(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)
37

38
(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
39
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship_2fa_sms_default_phone_number)
40

41
Please enter the 6 digit code:
42
Requesting session...
43

44
Looking for related GitHub issues on fastlane/fastlane...
45

46
➡️  `download_dsyms` fails to use session from spaceauth
47
    https://github.com/fastlane/fastlane/issues/18763 [closed] 2 💬
48
    3 weeks ago
49

50
➡️  match permission denied
51
    https://github.com/fastlane/fastlane/issues/17810 [closed] 11 💬
52

53
    26 Apr 2021
54

55
[!] The request could not be completed because:
56
	Unauthorized Access
57
➡️  Exception type: Spaceship::UnauthorizedAccessError
58
    https://github.com/fastlane/fastlane/issues/16510 [closed] 35 💬
59
    17 Sep 2020
60

61
and 21 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓
62

63
🔗  You can ⌘ + double-click on links to open them directly in your browser.
64
Error: Process completed with exit code 1.
Post Run actions/checkout@v2


> It looks like you got past the Expo build though, that's good. So now it's just a `fastlane` issue. I imagine the `FASTLANE_SESSION` environment variable might be incorrect, or perhaps the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`. You must also pass `FASTLANE_USER` and `FASTLANE_PASSWORD`. I think you're very close now though, it should just be some tweaking of those environment variables. You shouldn't see anything about 2fa in the output if it's working.

There is 2fa error if you read the error logs

**Comment by Forum-G** [comment]
> It looks like you got past the Expo build though, that's good. So now it's just a `fastlane` issue. I imagine the `FASTLANE_SESSION` environment variable might be incorrect, or perhaps the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`. You must also pass `FASTLANE_USER` and `FASTLANE_PASSWORD`. I think you're very close now though, it should just be some tweaking of those environment variables. You shouldn't see anything about 2fa in the output if it's working.

I already have env variables set up correctly, it is 2fa error , asking me to set up sms or something
![image](https://user-images.githubusercontent.com/84411852/128057967-01f8d9af-62e0-4e26-8177-e7fbcf9144e7.png)

**Comment by Forum-G** [comment]
Session loaded from environment variable is not valid. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account ''
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input sms to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship_2fa_sms_default_phone_number)




idk if I set up this variable right or not but this is what I added : 
 - run: fastlane pilot upload
        env:
            FASTLANE_USER: ${{secrets.EXPO_APPLE_ID}}
            FASTLANE_PASSWORD: ${{secrets.EXPO_APPLEPASS}}
            FASTLANE_SESSION: ${{secrets.FASTLANE_SESSION}}
            FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD}}
            SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER : +1-000-000-0000 (my actual phone number)

**Comment by mhoran** [comment]
> There is 2fa error if you read the error logs

Yes, but now it's `fastlane` failing, not Expo. Be sure your `FASTLANE_SESSION` is exactly as it is presented by `fastlane spaceauth`, quotes and all. The fact that you're getting errors about 2fa means that it's not using the `FASTLANE_SESSION` and falling back to 2fa.

You won't need the `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` in CI, once the `FASTLANE_SESSION` is working.

The difference between your logs and mine are as follows:
```
[14:35:47]: Login to App Store Connect (***)
Session loaded from environment variable is not valid. Continuing with normal login.
[14:35:51]: Login successful
```

**Comment by mhoran** [comment]
Your `FASTLANE_SESSION` needs to look exactly like the lines printed by `fastlane spaceauth` including that `\n` at the end and the `---` at the beginning. Make sure it's all one continuous line when pasted into `FASTLANE_SESSION`.

Also I just noticed that there is a new version of `fastlane` required for compatible with Apple login changes. So make sure you use the latest version of `fastlane` locally to generate that cookie.

**Comment by ForumG-SC** [comment]
> Your `FASTLANE_SESSION` needs to look exactly like the lines printed by `fastlane spaceauth` including that `\n` at the end and the `---` at the beginning. Make sure it's all one continuous line when pasted into `FASTLANE_SESSION`.
> 
> Also I just noticed that there is a new version of `fastlane` required for compatible with Apple login changes. So make sure you use the latest version of `fastlane` locally to generate that cookie.

I used this command : fastlane spaceauth -u myemailid
I did not manually enter my session to secret, I just said yes to copy session and pasted in the secret but yeah I do see there is new version
<img width="712" alt="Screen Shot 2021-08-03 at 1 45 24 PM" src="https://user-images.githubusercontent.com/84411852/128062020-bcda2337-d7c1-4070-a496-99feda25a111.png">

**Comment by mhoran** [comment]
I deleted your comment because it had a screenshot with the session value which gives access to your Apple account. You might want to change your Apple password.

Based on what I saw, I'm not sure how it copies (I don't get the copy option on Linux), but make sure the value in your GitHub secret is just the value within the `'`, not `export FASTLANE_SESSION='`. It should just be the value to the right of the `=`, *without* the `'` at the beginning and end.

**Comment by Forum-G** [comment]
> I deleted your comment because it had a screenshot with the session value which gives access to your Apple account. You might want to change your Apple password.
> 
> Based on what I saw, I'm not sure how it copies (I don't get the copy option on Linux), but make sure the value in your GitHub secret is just the value within the `'`, not `export FASTLANE_SESSION='`. It should just be the value to the right of the `=`, _without_ the `'` at the beginning and end.

Thanks , that was example not the actual session...  but I will check the quotes and make sure it the value after assignment operator and rerun and test. I just checked it by default copies the value from -- and not ' which is correct.

**Comment by ForumG-SC** [comment]
@mhoran  What am I doing wrong ? 
<img width="1089" alt="Screen Shot 2021-08-03 at 2 25 15 PM" src="https://user-images.githubusercontent.com/84411852/128067081-de70b533-0c49-4501-8bb1-d1d26179fde3.png">

**Comment by Forum-G** [comment]
Quick Question: Why does it takes 36mins + to finish this workflow process? Is there a way to speed this up? @mhoran 

<img width="930" alt="image" src="https://user-images.githubusercontent.com/84411852/128076187-b0e4971d-a7bd-434d-bfee-7cc995ab21ed.png">

**Comment by Forum-G** [comment]
Thank you for your help, it worked. :)

**Comment by mhoran** [comment]
Excellent! Yeah, the lag on the upload is really annoying, but that's all on Apple's end. Fastlane waits for the release to be ready for submission before returning, so that it can make it available to testers. I *think* you can shut this off if you'd like, but I don't remember how.

**Comment by Forum-G** [comment]
@mhoran  Quick Question, How to have app deployed to testflight starting with version number like 0.1 instead starting with 1?

**Comment by mhoran** [comment]
I believe Expo gets its version from `app.json` Whatever version is baked into the `.ipa` produced by Expo will be picked up by the App Store.

**Comment by Forum-G** [comment]
> I believe Expo gets its version from `app.json` Whatever version is baked into the `.ipa` produced by Expo will be picked up by the App Store.

App.json has expo tag which includes version :1.0.0 and than ios with bundler identifier there it says build number 1.0.0, so I would have to change both the number to 0.0.1 from 1.0.0(expo:version and ios:Buildnumber) in app.json and than I would run this workflow ?

**Comment by Forum-G** [comment]
@mhoran  Have modified any further settings for the workflow ? Every time you push a change it starts running, is there way to make it run only when we want?

**Comment by mhoran** [comment]
> App.json has expo tag which includes version :1.0.0 and than ios with bundler identifier there it says build number 1.0.0, so I would have to change both the number to 0.0.1 from 1.0.0(expo:version and ios:Buildnumber) in app.json and than I would run this workflow ?

Yes, that should do it. I don't think you need to change the `ios:Buildnumber` though; unless you want to release _new builds_ for a given version. So e.g. `0.0.1` build 1. All my builds are build 1; I just bump the version number when I build.

> @mhoran Have modified any further settings for the workflow ? Every time you push a change it starts running, is there way to make it run only when we want?

I only run the workflow for new GitHub releases. See https://github.com/mhoran/weechatRN/blob/master/.github/workflows/publish.yml#L3-L5.

**Comment by Forum-G** [comment]
Thanks😊😊

**Comment by Forum-G** [comment]
If the repo is set up using yarn packages not npm, this workflow will still work? @mhoran

**Comment by mhoran** [comment]
I think so long as you use `npm` in place of `yarn` it should, but I haven't tried this myself.
